var HPMSattributes = ["ROUTE_ID",
"BEGIN_POINT",
"END_POINT",
"ROUTE_NUMBER",
"ROUTE_NAME",
"ROUTE_QUALIFIER",
"ROUTE_SIGNING",
"F_SYSTEM",
"FACILITY_TYPE",
"URBAN_ID",
"COUNTY_ID",
"NHS",
"THROUGH_LANES",
"SPEED_LIMIT",
"OWNERSHIP",
"AADT",
"AADT_SINGLE_UNIT",
"AADT_COMBINATION",
"SURFACE_TYPE",
"IRI",
"PSR",
"TRUCK",
"ACCESS_CONTROL"]

var popupRoadAttributes = {
    "title":"Segment",
    "content":[{"type":"fields",
                "fieldInfos":[
                    {"fieldName":"ROUTE_ID",
                    "label":"Route Identification",
                    "isEditable":false,
                    "tooltip": "",
                    "visible": true,
                    "format": null,
                    "stringFieldOption": "text-box"},

                    {"fieldName":"BEGIN_POINT",
                               "label":"Begin Mile Point",
                               "isEditable":false,
                               "tooltip": "",
                                "visible": true,
                                "format": null,
                                "stringFieldOption": "text-box"},

                    {"fieldName":"END_POINT",
                               "label":"End Mile Point",
                               "isEditable":false,
                               "tooltip": "",
                                "visible": true,
                                "format": null,
                                "stringFieldOption": "text-box"},

                    {"fieldName":"ROUTE_NUMBER",
                               "label":"Route Number",
                               "isEditable":false,
                               "tooltip": "",
                                "visible": true,
                                "format": null,
                                "stringFieldOption": "text-box"},

                    {"fieldName":"ROUTE_NAME",
                               "label":"Route Name",
                               "isEditable":false,
                               "tooltip": "",
                                "visible": true,
                                "format": null,
                                "stringFieldOption": "text-box"},

                    {"fieldName":"ROUTE_QUALIFIER",
                               "label":"Route Qualifier",
                               "isEditable":false,
                               "tooltip": "",
                                "visible": true,
                                "format": null,
                                "stringFieldOption": "text-box"},

                    {"fieldName":"ROUTE_SIGNING",
                               "label":"Route Signing",
                               "isEditable":false,
                               "tooltip": "",
                                "visible": true,
                                "format": null,
                                "stringFieldOption": "text-box"},
                                
                    {"fieldName":"F_SYSTEM",
                               "label":"Functional Classification",
                               "isEditable":false,
                               "tooltip": "",
                                "visible": true,
                                "format": null,
                                "stringFieldOption": "text-box"},
                                
                    {"fieldName":"FACILITY_TYPE",
                               "label":"Facility Type",
                               "isEditable":false,
                               "tooltip": "",
                                "visible": true,
                                "format": null,
                                "stringFieldOption": "text-box"},

                    {"fieldName":"URBAN_ID",
                               "label":"Urban_Code",
                               "isEditable":false,
                               "tooltip": "",
                                "visible": true,
                                "format": null,
                                "stringFieldOption": "text-box"},

                    {"fieldName":"COUNTY_ID",
                               "label":"County Code",
                               "isEditable":false,
                               "tooltip": "",
                                "visible": true,
                                "format": null,
                                "stringFieldOption": "text-box"},
                                
                    {"fieldName":"NHS",
                               "label":"National Highway System",
                               "isEditable":false,
                               "tooltip": "",
                                "visible": true,
                                "format": null,
                                "stringFieldOption": "text-box"},

                    {"fieldName":"THROUGH_LANES",
                               "label":"Through Lanes",
                               "isEditable":false,
                               "tooltip": "",
                                "visible": true,
                                "format": null,
                                "stringFieldOption": "text-box"},

                    {"fieldName":"SPEED_LIMIT",
                               "label":"Posted Speed Limt",
                               "isEditable":false,
                               "tooltip": "",
                                "visible": true,
                                "format": null,
                                "stringFieldOption": "text-box"},
                                
                    {"fieldName":"OWNERSHIP",
                               "label":"Highway Ownership",
                               "isEditable":false,
                                "visible": true,
                                "format": null,
                                "stringFieldOption": "text-box"},

                    {"fieldName":"AADT",
                               "label":"Annual Average Daily Traffic",
                               "isEditable":false,
                               "tooltip": "",
                                "visible": true,
                                "format": null,
                                "stringFieldOption": "text-box"},
                                
                    {"fieldName":"AADT_SINGLE_UNIT",
                               "label":"AADT Single Unit",
                               "isEditable":false,
                                "visible": true,
                                "format": null,
                                "stringFieldOption": "text-box"},

                    {"fieldName":"AADT_COMBINATION",
                               "label":"AADT Combination",
                               "isEditable":false,
                               "tooltip": "",
                                "visible": true,
                                "format": null,
                                "stringFieldOption": "text-box"},

                    {"fieldName":"SURFACE_TYPE",
                                "label":"Surface Type",
                                "isEditable":false,
                                "tooltip": "",
                                 "visible": true,
                                 "format": null,
                                 "stringFieldOption": "text-box"},

                    {"fieldName":"IRI",
                               "label":"International Roughness Index",
                               "isEditable":false,
                               "tooltip": "",
                                "visible": true,
                                "format": null,
                                "stringFieldOption": "text-box"},
                                
                    {"fieldName":"PSR",
                               "label":"Present Servivability Rating",
                               "isEditable":false,
                                "visible": true,
                                "format": null,
                                "stringFieldOption": "text-box"},

                    {"fieldName":"NN",
                                "label":"National Network",
                                "isEditable":false,
                                "tooltip": "",
                                 "visible": true,
                                 "format": null,
                                 "stringFieldOption": "text-box"},
                                 
                     {"fieldName":"ACCESS_CONTROL",
                                "label":"Access Control",
                                "isEditable":false,
                                 "visible": true,
                                 "format": null,
                                 "stringFieldOption": "text-box"}
                            ]}]
     }